ARG OS_VERSION=22.04
ARG SRSRAN_BRANCH=release_23_11

##################
# Stage 1: Build #
##################
FROM ubuntu:$OS_VERSION AS builder

# Install dependencies
# We need uhd so enb and ue are built
# Use curl and unzip to get a specific commit state from github
# Also install ping to test connections
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    build-essential \
    cmake \
    libuhd-dev \
    uhd-host \
    curl \
    unzip \
    libboost-program-options-dev \
    libfftw3-dev \
    libmbedtls-dev \
    libboost-program-options-dev \
    libconfig++-dev \
    libsctp-dev \
    libzmq3-dev && \
    rm -rf /var/lib/apt/lists/*

ARG SRSRAN_BRANCH
RUN git clone --depth 1 --branch ${SRSRAN_BRANCH} https://github.com/srsran/srsRAN_4G.git /src

WORKDIR /src/build

RUN cmake ../
RUN make -j"$(nproc)"
RUN make install

# ################
# # Stage 2: Run #
# ################

FROM ubuntu:$OS_VERSION AS ue

COPY --from=builder /usr/local /usr/local

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    iputils-ping \
    iproute2 \
    iptables \
    iperf3 \
    libboost-program-options1.74.0 \
    libfftw3-3 \
    libmbedtls14 \
    libzmq3-dev && \
    rm -rf /var/lib/apt/lists/*

# Update dynamic linker
RUN ldconfig

WORKDIR /opt

COPY srsue/startup.sh startup.sh

# Run commands with line buffered standard output
# (-> get log messages in real time)

CMD ["/bin/bash","-c","./startup.sh"]
