FROM ubuntu:22.04 AS ue

# Install dependencies
# We need uhd so enb and ue are built
# Use curl and unzip to get a specific commit state from github
# Also install ping to test connections
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
     cmake \
     libuhd-dev \
     uhd-host \
     libboost-program-options-dev \
     libfftw3-dev \
     libmbedtls-dev \
     libsctp-dev \
     libconfig++-dev \
     libzmq3-dev \
     curl \
     iputils-ping \
     iproute2 \
     iptables \
     unzip \
     iperf3 \
     git \
     ca-certificates \
 && rm -rf /var/lib/apt/lists/*

ADD srsue/startup.sh /opt/startup.sh

RUN git clone --branch release_23_11 https://github.com/srsran/srsRAN_4G.git /srslte/

WORKDIR /srslte/build

RUN cmake ../
RUN make -j$(nproc)
RUN make install

# Update dynamic linker
RUN ldconfig

WORKDIR /srslte

RUN cp build/srsue/src/srsue /opt/srsue

WORKDIR /opt
RUN chmod +x startup.sh
# Run commands with line buffered standard output
# (-> get log messages in real time)
#ENTRYPOINT [ "stdbuf", "-o", "L" ]

CMD ["/bin/bash","-c","./startup.sh"]
